#include "GLFunctions.h"

#ifdef OS_WINDOWS

#define glGetProcAddress wglGetProcAddress
#define GL_GET_PROC_ADR(proc_type, proc_name) g_##proc_name = (proc_type) glGetProcAddress(#proc_name)

#elif defined(VERO4K) || defined(ODROID) || defined(VC)

#define GL_GET_PROC_ADR(proc_type, proc_name) g_##proc_name = (proc_type) dlsym(gles2so, #proc_name);

#elif defined(EGL)

#define glGetProcAddress eglGetProcAddress
#define GL_GET_PROC_ADR(proc_type, proc_name) Real##proc_name = (proc_type) glGetProcAddress("gl"#proc_name)
#define GL_GET_PROC_ADR_EGL(proc_type, proc_name) Real##proc_name = (proc_type) glGetProcAddress("egl"#proc_name)

#elif defined(OS_LINUX)

#include <X11/Xutil.h>
typedef XID GLXContextID;
typedef XID GLXPixmap;
typedef XID GLXDrawable;
typedef XID GLXPbuffer;
typedef XID GLXWindow;
typedef XID GLXFBConfigID;
typedef struct __GLXcontextRec *GLXContext;
typedef struct __GLXFBConfigRec *GLXFBConfig;
#define GLX_GLXEXT_PROTOTYPES
#include <GL/glxext.h>
#define glGetProcAddress glXGetProcAddress
#define GL_GET_PROC_ADR(proc_type, proc_name) g_##proc_name = (proc_type) glGetProcAddress((const GLubyte*)#proc_name)

#elif defined(OS_MAC_OS_X)
#include <dlfcn.h>

static void* AppleGLGetProcAddress (const char *name)
{
	static void* image = NULL;
	if (NULL == image)
		image = dlopen("/System/Library/Frameworks/OpenGL.framework/Versions/Current/OpenGL", RTLD_LAZY);

	return (image ? dlsym(image, name) : NULL);
}
#define glGetProcAddress AppleGLGetProcAddress
#define GL_GET_PROC_ADR(proc_type, proc_name) g_##proc_name = (proc_type) glGetProcAddress(#proc_name)

#elif defined(OS_IOS)
#include <dlfcn.h>

static void* IOSGLGetProcAddress (const char *name)
{
    return dlsym(RTLD_DEFAULT, name);
}

#define glGetProcAddress IOSGLGetProcAddress
#define GL_GET_PROC_ADR(proc_type, proc_name) g_##proc_name = (proc_type)glGetProcAddress(#proc_name)

#endif

//GL Fucntions

#ifdef OS_WINDOWS
PFNGLACTIVETEXTUREPROC RealActiveTexture;
PFNGLBLENDCOLORPROC RealBlendColor;
#elif defined(EGL) || defined(OS_IOS)
PFNGLBLENDFUNCPROC RealBlendFunc;
PFNGLPIXELSTOREIPROC RealPixelStorei;
PFNGLCLEARCOLORPROC RealClearColor;
PFNGLCULLFACEPROC RealCullFace;
PFNGLDEPTHFUNCPROC RealDepthFunc;
PFNGLDEPTHMASKPROC RealDepthMask;
PFNGLDISABLEPROC RealDisable;
PFNGLENABLEPROC RealEnable;
PFNGLPOLYGONOFFSETPROC RealPolygonOffset;
PFNGLSCISSORPROC RealScissor;
PFNGLVIEWPORTPROC RealViewport;
PFNGLBINDTEXTUREPROC RealBindTexture;
PFNGLTEXIMAGE2DPROC RealTexImage2D;
PFNGLTEXPARAMETERIPROC RealTexParameteri;
PFNGLGETINTEGERVPROC RealGetIntegerv;
PFNGLGETSTRINGPROC RealGetString;
PFNGLREADPIXELSPROC RealReadPixels;
PFNGLTEXSUBIMAGE2DPROC RealTexSubImage2D;
PFNGLDRAWARRAYSPROC RealDrawArrays;
PFNGLGETERRORPROC RealGetError;
PFNGLDRAWELEMENTSPROC RealDrawElements;
PFNGLLINEWIDTHPROC RealLineWidth;
PFNGLCLEARPROC RealClear;
PFNGLGETFLOATVPROC RealGetFloatv;
PFNGLDELETETEXTURESPROC RealDeleteTextures;
PFNGLGENTEXTURESPROC RealGenTextures;
PFNGLTEXPARAMETERFPROC RealTexParameterf;
PFNGLACTIVETEXTUREPROC RealActiveTexture;
PFNGLBLENDCOLORPROC RealBlendColor;
PFNGLREADBUFFERPROC RealReadBuffer;
PFNGLFINISHPROC RealFinish;
#if defined(OS_ANDROID)
PFNEGLGETNATIVECLIENTBUFFERANDROIDPROC RealGetNativeClientBufferANDROID;
#endif
#endif
PFNGLCREATESHADERPROC RealCreateShader;
PFNGLCOMPILESHADERPROC RealCompileShader;
PFNGLSHADERSOURCEPROC RealShaderSource;
PFNGLCREATEPROGRAMPROC RealCreateProgram;
PFNGLATTACHSHADERPROC RealAttachShader;
PFNGLLINKPROGRAMPROC RealLinkProgram;
PFNGLUSEPROGRAMPROC RealUseProgram;
PFNGLGETUNIFORMLOCATIONPROC RealGetUniformLocation;
PFNGLUNIFORM1IPROC RealUniform1i;
PFNGLUNIFORM1FPROC RealUniform1f;
PFNGLUNIFORM2FPROC RealUniform2f;
PFNGLUNIFORM2IPROC RealUniform2i;
PFNGLUNIFORM4IPROC RealUniform4i;
PFNGLUNIFORM4FPROC RealUniform4f;
PFNGLUNIFORM3FVPROC RealUniform3fv;
PFNGLUNIFORM4FVPROC RealUniform4fv;
PFNGLDETACHSHADERPROC RealDetachShader;
PFNGLDELETESHADERPROC RealDeleteShader;
PFNGLDELETEPROGRAMPROC RealDeleteProgram;
PFNGLGETPROGRAMINFOLOGPROC RealGetProgramInfoLog;
PFNGLGETSHADERINFOLOGPROC RealGetShaderInfoLog;
PFNGLGETSHADERIVPROC RealGetShaderiv;
PFNGLGETPROGRAMIVPROC RealGetProgramiv;

PFNGLENABLEVERTEXATTRIBARRAYPROC RealEnableVertexAttribArray;
PFNGLDISABLEVERTEXATTRIBARRAYPROC RealDisableVertexAttribArray;
PFNGLVERTEXATTRIBPOINTERPROC RealVertexAttribPointer;
PFNGLBINDATTRIBLOCATIONPROC RealBindAttribLocation;
PFNGLVERTEXATTRIB1FPROC RealVertexAttrib1f;
PFNGLVERTEXATTRIB4FPROC RealVertexAttrib4f;
PFNGLVERTEXATTRIB4FVPROC RealVertexAttrib4fv;

// multitexture functions
PFNGLDEPTHRANGEFPROC RealDepthRangef;
PFNGLCLEARDEPTHFPROC RealClearDepthf;

PFNGLDRAWBUFFERSPROC RealDrawBuffers;
PFNGLBINDFRAMEBUFFERPROC RealBindFramebuffer;
PFNGLDELETEFRAMEBUFFERSPROC RealDeleteFramebuffers;
PFNGLGENFRAMEBUFFERSPROC RealGenFramebuffers;
PFNGLFRAMEBUFFERTEXTURE2DPROC RealFramebufferTexture2D;
PFNGLTEXIMAGE2DMULTISAMPLEPROC RealTexImage2DMultisample;
PFNGLTEXSTORAGE2DMULTISAMPLEPROC RealTexStorage2DMultisample;
PFNGLGENRENDERBUFFERSPROC RealGenRenderbuffers;
PFNGLBINDRENDERBUFFERPROC RealBindRenderbuffer;
PFNGLRENDERBUFFERSTORAGEPROC RealRenderbufferStorage;
PFNGLFRAMEBUFFERRENDERBUFFERPROC RealFramebufferRenderbuffer;
PFNGLDELETERENDERBUFFERSPROC RealDeleteRenderbuffers;
PFNGLCHECKFRAMEBUFFERSTATUSPROC RealCheckFramebufferStatus;
PFNGLBLITFRAMEBUFFERPROC RealBlitFramebuffer;
PFNGLGENVERTEXARRAYSPROC RealGenVertexArrays;
PFNGLBINDVERTEXARRAYPROC RealBindVertexArray;
PFNGLDELETEVERTEXARRAYSPROC RealDeleteVertexArrays;
PFNGLGENBUFFERSPROC RealGenBuffers;
PFNGLBINDBUFFERPROC RealBindBuffer;
PFNGLBUFFERDATAPROC RealBufferData;
PFNGLMAPBUFFERPROC RealMapBuffer;
PFNGLMAPBUFFERRANGEPROC RealMapBufferRange;
PFNGLUNMAPBUFFERPROC RealUnmapBuffer;
PFNGLDELETEBUFFERSPROC RealDeleteBuffers;
PFNGLBINDIMAGETEXTUREPROC RealBindImageTexture;
PFNGLMEMORYBARRIERPROC RealMemoryBarrier;
PFNGLGETSTRINGIPROC RealGetStringi;
PFNGLINVALIDATEFRAMEBUFFERPROC RealInvalidateFramebuffer;
PFNGLBUFFERSTORAGEPROC RealBufferStorage;
PFNGLFENCESYNCPROC RealFenceSync;
PFNGLCLIENTWAITSYNCPROC RealClientWaitSync;
PFNGLDELETESYNCPROC RealDeleteSync;

PFNGLGETUNIFORMBLOCKINDEXPROC RealGetUniformBlockIndex;
PFNGLUNIFORMBLOCKBINDINGPROC RealUniformBlockBinding;
PFNGLGETACTIVEUNIFORMBLOCKIVPROC RealGetActiveUniformBlockiv;
PFNGLGETUNIFORMINDICESPROC RealGetUniformIndices;
PFNGLGETACTIVEUNIFORMSIVPROC RealGetActiveUniformsiv;
PFNGLBINDBUFFERBASEPROC RealBindBufferBase;
PFNGLBUFFERSUBDATAPROC RealBufferSubData;

PFNGLGETPROGRAMBINARYPROC RealGetProgramBinary;
PFNGLPROGRAMBINARYPROC RealProgramBinary;
PFNGLPROGRAMPARAMETERIPROC RealProgramParameteri;

PFNGLTEXSTORAGE2DPROC RealTexStorage2D;
PFNGLTEXTURESTORAGE2DPROC RealTextureStorage2D;
PFNGLTEXTURESUBIMAGE2DPROC RealTextureSubImage2D;
PFNGLTEXTURESTORAGE2DMULTISAMPLEEXTPROC RealTextureStorage2DMultisample;
PFNGLTEXTUREPARAMETERIPROC RealTextureParameteri;
PFNGLTEXTUREPARAMETERFPROC RealTextureParameterf;
PFNGLCREATETEXTURESPROC RealCreateTextures;
PFNGLCREATEBUFFERSPROC RealCreateBuffers;
PFNGLCREATEFRAMEBUFFERSPROC RealCreateFramebuffers;
PFNGLNAMEDFRAMEBUFFERTEXTUREPROC RealNamedFramebufferTexture;
PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC RealDrawRangeElementsBaseVertex;
PFNGLFLUSHMAPPEDBUFFERRANGEPROC RealFlushMappedBufferRange;
PFNGLTEXTUREBARRIERPROC RealTextureBarrier;
PFNGLTEXTUREBARRIERNVPROC RealTextureBarrierNV;
PFNGLCLEARBUFFERFVPROC RealClearBufferfv;
PFNGLENABLEIPROC RealEnablei;
PFNGLDISABLEIPROC RealDisablei;
PFNGLEGLIMAGETARGETTEXTURE2DOESPROC RealEGLImageTargetTexture2DOES;

void initGLFunctions()
{
#ifdef VC
	void *gles2so = dlopen("/opt/vc/lib/libbrcmGLESv2.so", RTLD_NOW);
#elif defined(ODROID)
	void *gles2so = dlopen("/usr/lib/arm-linux-gnueabihf/libGLESv2.so", RTLD_NOW);
#elif defined(VERO4K)
       void *gles2so = dlopen("/opt/vero3/lib/libGLESv2.so", RTLD_NOW);
#endif
#ifdef OS_WINDOWS
	GL_GET_PROC_ADR(PFNGLACTIVETEXTUREPROC, ActiveTexture);
	GL_GET_PROC_ADR(PFNGLBLENDCOLORPROC, BlendColor);
#elif defined(EGL) || defined(OS_IOS)
	GL_GET_PROC_ADR(PFNGLBLENDFUNCPROC, BlendFunc);
	GL_GET_PROC_ADR(PFNGLPIXELSTOREIPROC, PixelStorei);
	GL_GET_PROC_ADR(PFNGLCLEARCOLORPROC, ClearColor);
	GL_GET_PROC_ADR(PFNGLCULLFACEPROC, CullFace);
	GL_GET_PROC_ADR(PFNGLDEPTHFUNCPROC, DepthFunc);
	GL_GET_PROC_ADR(PFNGLDEPTHMASKPROC, DepthMask);
	GL_GET_PROC_ADR(PFNGLDISABLEPROC, Disable);
	GL_GET_PROC_ADR(PFNGLENABLEPROC, Enable);
	GL_GET_PROC_ADR(PFNGLPOLYGONOFFSETPROC, PolygonOffset);
	GL_GET_PROC_ADR(PFNGLSCISSORPROC, Scissor);
	GL_GET_PROC_ADR(PFNGLVIEWPORTPROC, Viewport);
	GL_GET_PROC_ADR(PFNGLBINDTEXTUREPROC, BindTexture);
	GL_GET_PROC_ADR(PFNGLTEXIMAGE2DPROC, TexImage2D);
	GL_GET_PROC_ADR(PFNGLTEXPARAMETERIPROC, TexParameteri);
	GL_GET_PROC_ADR(PFNGLGETINTEGERVPROC, GetIntegerv);
	GL_GET_PROC_ADR(PFNGLGETSTRINGPROC, GetString);
	GL_GET_PROC_ADR(PFNGLREADPIXELSPROC, ReadPixels);
	GL_GET_PROC_ADR(PFNGLTEXSUBIMAGE2DPROC, TexSubImage2D);
	GL_GET_PROC_ADR(PFNGLDRAWARRAYSPROC, DrawArrays);
	GL_GET_PROC_ADR(PFNGLGETERRORPROC, GetError);
	GL_GET_PROC_ADR(PFNGLDRAWELEMENTSPROC, DrawElements);
	GL_GET_PROC_ADR(PFNGLLINEWIDTHPROC, LineWidth);
	GL_GET_PROC_ADR(PFNGLCLEARPROC, Clear);
	GL_GET_PROC_ADR(PFNGLGETFLOATVPROC, GetFloatv);
	GL_GET_PROC_ADR(PFNGLDELETETEXTURESPROC, DeleteTextures);
	GL_GET_PROC_ADR(PFNGLGENTEXTURESPROC, GenTextures);
	GL_GET_PROC_ADR(PFNGLTEXPARAMETERFPROC, TexParameterf);
	GL_GET_PROC_ADR(PFNGLACTIVETEXTUREPROC, ActiveTexture);
	GL_GET_PROC_ADR(PFNGLBLENDCOLORPROC, BlendColor);
	GL_GET_PROC_ADR(PFNGLREADBUFFERPROC, ReadBuffer);
	GL_GET_PROC_ADR(PFNGLFINISHPROC, Finish);
	GL_GET_PROC_ADR_EGL(PFNEGLGETNATIVECLIENTBUFFERANDROIDPROC, GetNativeClientBufferANDROID);
#endif

	GL_GET_PROC_ADR(PFNGLCREATESHADERPROC, CreateShader);
	GL_GET_PROC_ADR(PFNGLCOMPILESHADERPROC, CompileShader);
	GL_GET_PROC_ADR(PFNGLSHADERSOURCEPROC, ShaderSource);
	GL_GET_PROC_ADR(PFNGLCREATEPROGRAMPROC, CreateProgram);
	GL_GET_PROC_ADR(PFNGLATTACHSHADERPROC, AttachShader);
	GL_GET_PROC_ADR(PFNGLLINKPROGRAMPROC, LinkProgram);
	GL_GET_PROC_ADR(PFNGLUSEPROGRAMPROC, UseProgram);
	GL_GET_PROC_ADR(PFNGLGETUNIFORMLOCATIONPROC, GetUniformLocation);
	GL_GET_PROC_ADR(PFNGLUNIFORM1IPROC, Uniform1i);
	GL_GET_PROC_ADR(PFNGLUNIFORM1FPROC, Uniform1f);
	GL_GET_PROC_ADR(PFNGLUNIFORM2FPROC, Uniform2f);
	GL_GET_PROC_ADR(PFNGLUNIFORM2IPROC, Uniform2i);
	GL_GET_PROC_ADR(PFNGLUNIFORM4IPROC, Uniform4i);
	GL_GET_PROC_ADR(PFNGLUNIFORM4FPROC, Uniform4f);
	GL_GET_PROC_ADR(PFNGLUNIFORM3FVPROC, Uniform3fv);
	GL_GET_PROC_ADR(PFNGLUNIFORM4FVPROC, Uniform4fv);
	GL_GET_PROC_ADR(PFNGLDETACHSHADERPROC, DetachShader);
	GL_GET_PROC_ADR(PFNGLDELETESHADERPROC, DeleteShader);
	GL_GET_PROC_ADR(PFNGLDELETEPROGRAMPROC, DeleteProgram);
	GL_GET_PROC_ADR(PFNGLGETPROGRAMINFOLOGPROC, GetProgramInfoLog);
	GL_GET_PROC_ADR(PFNGLGETSHADERINFOLOGPROC, GetShaderInfoLog);
	GL_GET_PROC_ADR(PFNGLGETSHADERIVPROC, GetShaderiv);
	GL_GET_PROC_ADR(PFNGLGETPROGRAMIVPROC, GetProgramiv);

	GL_GET_PROC_ADR(PFNGLENABLEVERTEXATTRIBARRAYPROC, EnableVertexAttribArray);
	GL_GET_PROC_ADR(PFNGLDISABLEVERTEXATTRIBARRAYPROC, DisableVertexAttribArray);
	GL_GET_PROC_ADR(PFNGLVERTEXATTRIBPOINTERPROC, VertexAttribPointer);
	GL_GET_PROC_ADR(PFNGLBINDATTRIBLOCATIONPROC, BindAttribLocation);
	GL_GET_PROC_ADR(PFNGLVERTEXATTRIB1FPROC, VertexAttrib1f);
	GL_GET_PROC_ADR(PFNGLVERTEXATTRIB4FPROC, VertexAttrib4f);
	GL_GET_PROC_ADR(PFNGLVERTEXATTRIB4FVPROC, VertexAttrib4fv);

	GL_GET_PROC_ADR(PFNGLDEPTHRANGEFPROC, DepthRangef);
	GL_GET_PROC_ADR(PFNGLCLEARDEPTHFPROC, ClearDepthf);

	GL_GET_PROC_ADR(PFNGLDRAWBUFFERSPROC, DrawBuffers);
	GL_GET_PROC_ADR(PFNGLBINDFRAMEBUFFERPROC, BindFramebuffer);
	GL_GET_PROC_ADR(PFNGLDELETEFRAMEBUFFERSPROC, DeleteFramebuffers);
	GL_GET_PROC_ADR(PFNGLGENFRAMEBUFFERSPROC, GenFramebuffers);
	GL_GET_PROC_ADR(PFNGLFRAMEBUFFERTEXTURE2DPROC, FramebufferTexture2D);
	GL_GET_PROC_ADR(PFNGLTEXIMAGE2DMULTISAMPLEPROC, TexImage2DMultisample);
	GL_GET_PROC_ADR(PFNGLTEXSTORAGE2DMULTISAMPLEPROC, TexStorage2DMultisample);
	GL_GET_PROC_ADR(PFNGLGENRENDERBUFFERSPROC, GenRenderbuffers);
	GL_GET_PROC_ADR(PFNGLBINDRENDERBUFFERPROC, BindRenderbuffer);
	GL_GET_PROC_ADR(PFNGLRENDERBUFFERSTORAGEPROC, RenderbufferStorage);
	GL_GET_PROC_ADR(PFNGLFRAMEBUFFERRENDERBUFFERPROC, FramebufferRenderbuffer);
	GL_GET_PROC_ADR(PFNGLDELETERENDERBUFFERSPROC, DeleteRenderbuffers);
	GL_GET_PROC_ADR(PFNGLCHECKFRAMEBUFFERSTATUSPROC, CheckFramebufferStatus);
	GL_GET_PROC_ADR(PFNGLBLITFRAMEBUFFERPROC, BlitFramebuffer);
	GL_GET_PROC_ADR(PFNGLGENVERTEXARRAYSPROC, GenVertexArrays);
	GL_GET_PROC_ADR(PFNGLBINDVERTEXARRAYPROC, BindVertexArray);
	GL_GET_PROC_ADR(PFNGLDELETEVERTEXARRAYSPROC, DeleteVertexArrays);
	GL_GET_PROC_ADR(PFNGLGENBUFFERSPROC, GenBuffers);
	GL_GET_PROC_ADR(PFNGLBINDBUFFERPROC, BindBuffer);
	GL_GET_PROC_ADR(PFNGLBUFFERDATAPROC, BufferData);
	GL_GET_PROC_ADR(PFNGLMAPBUFFERPROC, MapBuffer);
	GL_GET_PROC_ADR(PFNGLMAPBUFFERRANGEPROC, MapBufferRange);
	GL_GET_PROC_ADR(PFNGLUNMAPBUFFERPROC, UnmapBuffer);
	GL_GET_PROC_ADR(PFNGLDELETEBUFFERSPROC, DeleteBuffers);
	GL_GET_PROC_ADR(PFNGLBINDIMAGETEXTUREPROC, BindImageTexture);
	GL_GET_PROC_ADR(PFNGLMEMORYBARRIERPROC, MemoryBarrier);
	GL_GET_PROC_ADR(PFNGLGETSTRINGIPROC, GetStringi);
	GL_GET_PROC_ADR(PFNGLINVALIDATEFRAMEBUFFERPROC, InvalidateFramebuffer);
	GL_GET_PROC_ADR(PFNGLBUFFERSTORAGEPROC, BufferStorage);
	GL_GET_PROC_ADR(PFNGLFENCESYNCPROC, FenceSync);
	GL_GET_PROC_ADR(PFNGLCLIENTWAITSYNCPROC, ClientWaitSync);
	GL_GET_PROC_ADR(PFNGLDELETESYNCPROC, DeleteSync);

	GL_GET_PROC_ADR(PFNGLGETUNIFORMBLOCKINDEXPROC, GetUniformBlockIndex);
	GL_GET_PROC_ADR(PFNGLUNIFORMBLOCKBINDINGPROC, UniformBlockBinding);
	GL_GET_PROC_ADR(PFNGLGETACTIVEUNIFORMBLOCKIVPROC, GetActiveUniformBlockiv);
	GL_GET_PROC_ADR(PFNGLGETUNIFORMINDICESPROC, GetUniformIndices);
	GL_GET_PROC_ADR(PFNGLGETACTIVEUNIFORMSIVPROC, GetActiveUniformsiv);
	GL_GET_PROC_ADR(PFNGLBINDBUFFERBASEPROC, BindBufferBase);
	GL_GET_PROC_ADR(PFNGLBUFFERSUBDATAPROC, BufferSubData);

	GL_GET_PROC_ADR(PFNGLGETPROGRAMBINARYPROC, GetProgramBinary);
	GL_GET_PROC_ADR(PFNGLPROGRAMBINARYPROC, ProgramBinary);
	GL_GET_PROC_ADR(PFNGLPROGRAMPARAMETERIPROC, ProgramParameteri);

	GL_GET_PROC_ADR(PFNGLTEXSTORAGE2DPROC, TexStorage2D);
	GL_GET_PROC_ADR(PFNGLTEXTURESTORAGE2DPROC, TextureStorage2D);
	GL_GET_PROC_ADR(PFNGLTEXTURESUBIMAGE2DPROC, TextureSubImage2D);
	GL_GET_PROC_ADR(PFNGLTEXTURESTORAGE2DMULTISAMPLEEXTPROC, TextureStorage2DMultisample);

	GL_GET_PROC_ADR(PFNGLTEXTUREPARAMETERIPROC, TextureParameteri);
	GL_GET_PROC_ADR(PFNGLTEXTUREPARAMETERFPROC, TextureParameterf);
	GL_GET_PROC_ADR(PFNGLCREATETEXTURESPROC, CreateTextures);
	GL_GET_PROC_ADR(PFNGLCREATEBUFFERSPROC, CreateBuffers);
	GL_GET_PROC_ADR(PFNGLCREATEFRAMEBUFFERSPROC, CreateFramebuffers);
	GL_GET_PROC_ADR(PFNGLNAMEDFRAMEBUFFERTEXTUREPROC, NamedFramebufferTexture);
	GL_GET_PROC_ADR(PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC, DrawRangeElementsBaseVertex);
	GL_GET_PROC_ADR(PFNGLFLUSHMAPPEDBUFFERRANGEPROC, FlushMappedBufferRange);
	GL_GET_PROC_ADR(PFNGLTEXTUREBARRIERPROC, TextureBarrier);
	GL_GET_PROC_ADR(PFNGLTEXTUREBARRIERNVPROC, TextureBarrierNV);
	GL_GET_PROC_ADR(PFNGLCLEARBUFFERFVPROC, ClearBufferfv);
	GL_GET_PROC_ADR(PFNGLENABLEIPROC, Enablei);
	GL_GET_PROC_ADR(PFNGLDISABLEIPROC, Disablei);
	GL_GET_PROC_ADR(PFNGLEGLIMAGETARGETTEXTURE2DOESPROC, EGLImageTargetTexture2DOES);
}
